---

- name: Include specific Elasticsearch
  include: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Elasticsearch
  include: elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include elasticsearch-ssl
  include: elasticsearch-ssl.yml
  when: es_ssl_directory != '' and es_ssl_directory_fileglob != ''
